import { Product, Order } from "./types";

export const initialProducts: Product[] = [
  {
    sku: "SL5-001",
    name: "Surface Laptop 5",
    description: "Ultra-thin 13.5\" touchscreen laptop with 12th Gen Intel Core i5, 8GB RAM, 256GB SSD. All-day battery life and premium Alcantara keyboard.",
    stock: 24,
    price: 1299.99,
    image: "/products/laptop.svg",
    category: "Laptops",
  },
  {
    sku: "SP10-004",
    name: "Surface Pro 10",
    description: "2-in-1 tablet with 13\" PixelSense display, Intel Core Ultra processor, and all-day battery. Includes Surface Pen support.",
    stock: 12,
    price: 1599.99,
    image: "/products/tablet.svg",
    category: "Tablets",
  },
  {
    sku: "XSX-008",
    name: "Xbox Series X",
    description: "The fastest, most powerful Xbox ever. 4K gaming at up to 120 FPS with 1TB custom SSD. Backwards compatible.",
    stock: 8,
    price: 499.99,
    image: "/products/console.svg",
    category: "Gaming",
  },
  {
    sku: "XWC-002",
    name: "Xbox Wireless Controller",
    description: "Enhanced gaming controller with textured grip, hybrid D-pad, and Bluetooth connectivity. Available in multiple colors.",
    stock: 150,
    price: 59.99,
    image: "/products/controller.svg",
    category: "Gaming",
  },
  {
    sku: "SH3-006",
    name: "Surface Headphones 3",
    description: "Premium wireless headphones with adaptive ANC, Omnisonic sound, and 15-hour battery. Touch controls on ear cups.",
    stock: 35,
    price: 249.99,
    image: "/products/headphones.svg",
    category: "Audio",
  },
  {
    sku: "M365-003",
    name: "Microsoft 365 Family",
    description: "Premium Office apps, 1TB cloud storage per person, for up to 6 people. Includes Word, Excel, PowerPoint, and more.",
    stock: 9999,
    price: 99.99,
    image: "/products/software.svg",
    category: "Software",
  },
  {
    sku: "AM-005",
    name: "Arc Mouse",
    description: "Ultra-slim portable Bluetooth mouse that snaps flat for easy travel. Innovative arc design with full scroll plane.",
    stock: 87,
    price: 79.99,
    image: "/products/mouse.svg",
    category: "Accessories",
  },
  {
    sku: "SK-007",
    name: "Surface Keyboard",
    description: "Slim full-size wireless keyboard with built-in number pad and quiet mechanical keys. Premium aluminum frame.",
    stock: 60,
    price: 99.99,
    image: "/products/keyboard.svg",
    category: "Accessories",
  },
  {
    sku: "SD-009",
    name: "Surface Dock 2",
    description: "Transform your Surface into a desktop workstation. Dual 4K monitor support, 199W power supply, USB-C and USB-A ports.",
    stock: 42,
    price: 259.99,
    image: "/products/dock.svg",
    category: "Accessories",
  },
  {
    sku: "SPE-010",
    name: "Surface Pen",
    description: "Natural writing experience with 4096 levels of pressure sensitivity. Tilt support for shading. Rechargeable battery.",
    stock: 95,
    price: 129.99,
    image: "/products/pen.svg",
    category: "Accessories",
  },
  {
    sku: "XGP-011",
    name: "Xbox Game Pass Ultimate",
    description: "3-month subscription. Hundreds of games on console, PC, and cloud. EA Play included. Day one access to new releases.",
    stock: 9999,
    price: 44.99,
    image: "/products/gamepass.svg",
    category: "Gaming",
  },
  {
    sku: "SEB-012",
    name: "Surface Earbuds",
    description: "True wireless earbuds with omnisonic sound, intuitive touch controls, and all-day comfort. Up to 24hr battery with case.",
    stock: 28,
    price: 199.99,
    image: "/products/earbuds.svg",
    category: "Audio",
  },
];

export const seedOrders: Order[] = [
  {
    id: "ORD-1001",
    customerName: "Alice Johnson",
    email: "alice@example.com",
    items: [{ sku: "SL5-001", name: "Surface Laptop 5", price: 1299.99, quantity: 1, image: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4OAgf" }],
    total: 1299.99,
    status: "delivered",
    createdAt: "2026-02-10T10:30:00Z",
    updatedAt: "2026-02-14T16:00:00Z",
    trackingNumber: "TRK-8843921",
    trackingEvents: [
      { status: "pending", timestamp: "2026-02-10T10:30:00Z", location: "Online", description: "Order placed" },
      { status: "processing", timestamp: "2026-02-10T14:00:00Z", location: "Contoso Warehouse, Redmond WA", description: "Order confirmed and being prepared" },
      { status: "shipped", timestamp: "2026-02-11T09:00:00Z", location: "Redmond WA", description: "Package picked up by carrier" },
      { status: "out_for_delivery", timestamp: "2026-02-14T08:00:00Z", location: "Seattle WA", description: "Out for delivery" },
      { status: "delivered", timestamp: "2026-02-14T16:00:00Z", location: "Seattle WA", description: "Delivered to front door" },
    ],
  },
  {
    id: "ORD-1002",
    customerName: "Bob Chen",
    email: "bob.chen@example.com",
    items: [{ sku: "XWC-002", name: "Xbox Wireless Controller", price: 59.99, quantity: 2, image: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4FlPl" }],
    total: 119.98,
    status: "shipped",
    createdAt: "2026-02-15T14:20:00Z",
    updatedAt: "2026-02-16T10:00:00Z",
    trackingNumber: "TRK-7741002",
    trackingEvents: [
      { status: "pending", timestamp: "2026-02-15T14:20:00Z", location: "Online", description: "Order placed" },
      { status: "processing", timestamp: "2026-02-15T16:00:00Z", location: "Contoso Warehouse, Redmond WA", description: "Order confirmed" },
      { status: "shipped", timestamp: "2026-02-16T10:00:00Z", location: "Redmond WA", description: "Package shipped via express" },
    ],
  },
  {
    id: "ORD-1003",
    customerName: "Carol Martinez",
    email: "carol.m@example.com",
    items: [{ sku: "M365-003", name: "Microsoft 365 Family", price: 99.99, quantity: 1, image: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4qXe0" }],
    total: 99.99,
    status: "processing",
    createdAt: "2026-02-16T09:15:00Z",
    updatedAt: "2026-02-16T11:00:00Z",
    trackingEvents: [
      { status: "pending", timestamp: "2026-02-16T09:15:00Z", location: "Online", description: "Order placed" },
      { status: "processing", timestamp: "2026-02-16T11:00:00Z", location: "Contoso Warehouse, Redmond WA", description: "Preparing your order" },
    ],
  },
];
